const pokemons = [
  { code: '1', name: 'Bulbasaur', type: ['Grass', 'Poison'],
  description: 'There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger.', 
  category: 'Seed', abilities: ['Overgrow'], gender: 'both', weaknesses: ['Fire', 'Psychic', 'Flying', 'Ice'],
  stats: {hp: 3, attack: 3, defense: 3, specialAttack: 4, specialDefense: 4, speed: 3}, 
  weight: 15.2, height: {ft: 2, in: 4}, evolutions: [1, 2, 3] },
  { code: '2', name: 'Ivysaur', type: ['Grass', 'Poison'],
  description: 'When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.', 
  category: 'Seed', abilities: ['Overgrow'], gender: 'both', weaknesses: ['Fire', 'Psychic', 'Flying', 'Ice'],
  stats: {hp: 3, attack: 3, defense: 3, specialAttack: 4, specialDefense: 4, speed: 3}, 
  weight: 28.7, height: {ft: 3, in: 3}, evolutions: [1, 2, 3] },
  { code: '3', name: 'Venusaur', type: ['Grass', 'Poison'], 
  description: 'Its plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.', 
  category: 'Seed', abilities: ['Overgrow'], gender: 'both', weaknesses: ['Fire', 'Psychic', 'Flying', 'Ice'],
  stats: {hp: 3, attack: 3, defense: 3, specialAttack: 4, specialDefense: 4, speed: 3}, 
  weight: 220.5, height: {ft: 6, in: 7}, evolutions: [1, 2, 3] },
  { code: '4', name: 'Charmander', type: ['Fire'],
  description: 'It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail.', 
  category: 'Lizard', abilities: ['Blaze'], gender: 'both', weaknesses: ['Water', 'Ground', 'Rock'],
  stats: {hp: 3, attack: 4, defense: 3, specialAttack: 4, specialDefense: 3, speed: 4}, 
  weight: 18.7, height: {ft: 2, in: 0}, evolutions: [4, 5, 6] },
  { code: '5', name: 'Charmeleon', type: ['Fire'],
  description: 'It has a barbaric nature. In battle, it whips its fiery tail around and slashes away with sharp claws.', 
  category: 'Flame', abilities: ['Blaze'], gender: 'both', weaknesses: ['Water', 'Ground', 'Rock'],
  stats: {hp: 4, attack: 4, defense: 4, specialAttack: 5, specialDefense: 4, speed: 5}, 
  weight: 41.9, height: {ft: 3, in: 7}, evolutions: [4, 5, 6] },
  { code: '6', name: 'Charizard', type: ['Fire', 'Flying'],
  description: 'It is said that Charizard’s fire burns hotter if it has experienced harsh battles.', 
  category: 'Flame', abilities: ['Blaze'], gender: 'both', weaknesses: ['Water', 'Electric', 'Rock'],
  stats: {hp: 5, attack: 5, defense: 5, specialAttack: 7, specialDefense: 5, speed: 6}, 
  weight: 199.5, height: {ft: 5, in: 7}, evolutions: [4, 5, 6] },
  { code: '7', name: 'Squirtle', type: ['Water'],
  description: 'When it retracts its long neck into its shell, it squirts out water with vigorous force.', 
  category: 'Tiny Turtle', abilities: ['Torrent'], gender: 'both', weaknesses: ['Grass', 'Electric'],
  stats: {hp: 3, attack: 3, defense: 4, specialAttack: 3, specialDefense: 4, speed: 3}, 
  weight: 19.8, height: {ft: 1, in: 8}, evolutions: [7, 8, 9] },
  { code: '8', name: 'Wartortle', type: ['Water'],
  description: 'It is recognized as a symbol of longevity. If its shell has algae on it, that Wartortle is very old.', 
  category: 'Turtle', abilities: ['Torrent'], gender: 'both', weaknesses: ['Grass', 'Electric'],
  stats: {hp: 4, attack: 4, defense: 5, specialAttack: 4, specialDefense: 5, speed: 4}, 
  weight: 49.6, height: {ft: 3, in: 3}, evolutions: [7, 8, 9] },
  { code: '9', name: 'Blastoise', type: ['Water'],
  description: 'It crushes its foe under its heavy body to cause fainting. In a pinch, it will withdraw inside its shell.', 
  category: 'Shellfish', abilities: ['Torrent'], gender: 'both', weaknesses: ['Grass', 'Electric'],
  stats: {hp: 5, attack: 5, defense: 6, specialAttack: 5, specialDefense: 7, speed: 5}, 
  weight: 188.5, height: {ft: 5, in: 3}, evolutions: [7, 8, 9] },
  { code: '10', name: 'Caterpie', type: ['Bug'],
  description: 'For protection, it releases a horrible stench from the antenna on its head to drive away enemies.', 
  category: 'Worm', abilities: ['Shield Dust'], gender: 'both', weaknesses: ['Fire', 'Flying', 'Rock'],
  stats: {hp: 3, attack: 2, defense: 3, specialAttack: 2, specialDefense: 2, speed: 3}, 
  weight: 6.4, height: {ft: 1, in: 0}, evolutions: [10, 11, 12] },
  { code: '11', name: 'Metapod', type: ['Bug'],
  description: 'It is waiting for the moment to evolve. At this stage, it can only harden, so it remains motionless to avoid attack.', 
  category: 'Cocoon', abilities: ['Shed Skin'], gender: 'both', weaknesses: ['Fire', 'Flying', 'Rock'],
  stats: {hp: 3, attack: 2, defense: 4, specialAttack: 2, specialDefense: 2, speed: 2}, 
  weight: 21.8, height: {ft: 2, in: 4}, evolutions: [10, 11, 12] },
  { code: '12', name: 'Butterfree', type: ['Bug', 'Flying'],
  description: 'It loves the nectar of flowers and can locate flower patches that have even tiny amounts of pollen.', 
  category: 'Butterfly', abilities: ['Compound Eyes'], gender: 'both', weaknesses: ['Fire', 'Flying', 'Electric', 'Ice', 'Rock'],
  stats: {hp: 4, attack: 3, defense: 3, specialAttack: 6, specialDefense: 5, speed: 5}, 
  weight: 70.5, height: {ft: 3, in: 7}, evolutions: [10, 11, 12] },
  { code: '13', name: 'Weedle', type: ['Bug', 'Poison'],
  description: 'Beware of the sharp stinger on its head. It hides in grass and bushes where it eats leaves.', 
  category: 'Hairy Bug', abilities: ['Shield Dust'], gender: 'both', weaknesses: ['Fire', 'Psychic', 'Flying', 'Rock'],
  stats: {hp: 3, attack: 3, defense: 2, specialAttack: 2, specialDefense: 2, speed: 3}, 
  weight: 7.1, height: {ft: 1, in: 0}, evolutions: [13, 14, 15] },
  { code: '14', name: 'Kakuna', type: ['Bug', 'Poison'],
  description: 'Able to move only slightly. When endangered, it may stick out its stinger and poison its enemy.', 
  category: 'Cocoon', abilities: ['Shed Skin'], gender: 'both', weaknesses: ['Fire', 'Psychic', 'Flying', 'Rock'],
  stats: {hp: 3, attack: 2, defense: 3, specialAttack: 2, specialDefense: 2, speed: 3}, 
  weight: 22.0, height: {ft: 2, in: 0}, evolutions: [13, 14, 15] },
  { code: '15', name: 'Beedrill', type: ['Bug', 'Poison'],
  description: 'It has three poisonous stingers on its forelegs and its tail. They are used to jab its enemy repeatedly.', 
  category: 'Poison Bee', abilities: ['Swarm'], gender: 'both', weaknesses: ['Fire', 'Psychic', 'Flying', 'Rock'],
  stats: {hp: 4, attack: 6, defense: 3, specialAttack: 3, specialDefense: 5, speed: 5}, 
  weight: 65.0, height: {ft: 3, in: 3}, evolutions: [13, 14, 15] },
  { code: '16', name: 'Pidgey', type: ['Normal', 'Flying'],
  description: 'Very docile. If attacked, it will often kick up sand to protect itself rather than fight back.', 
  category: 'Tiny Bird', abilities: ['Keen Eye', 'Tangled Feet'], gender: 'both', weaknesses: ['Electric', 'Ice', 'Rock'],
  stats: {hp: 3, attack: 3, defense: 3, specialAttack: 3, specialDefense: 3, speed: 4}, 
  weight: 4.0, height: {ft: 1, in: 0}, evolutions: [16, 17, 18] },
  { code: '17', name: 'Pidgeotto', type: ['Normal', 'Flying'],
  description: 'This Pokémon is full of vitality. It constantly flies around its large territory in search of prey.', 
  category: 'Bird', abilities: ['Keen Eye', 'Tangled Feet'], gender: 'both', weaknesses: ['Electric', 'Ice', 'Rock'],
  stats: {hp: 4, attack: 4, defense: 4, specialAttack: 3, specialDefense: 3, speed: 5}, 
  weight: 66.1, height: {ft: 3, in: 7}, evolutions: [16, 17, 18] },
  { code: '18', name: 'Pidgeot', type: ['Normal', 'Flying'],
  description: 'This Pokémon flies at Mach 2 speed, seeking prey. Its large talons are feared as wicked weapons.', 
  category: 'Bird', abilities: ['Keen Eye', 'Tangled Feet'], gender: 'both', weaknesses: ['Electric', 'Ice', 'Rock'],
  stats: {hp: 5, attack: 5, defense: 5, specialAttack: 5, specialDefense: 5, speed: 6}, 
  weight: 87.1, height: {ft: 4, in: 11}, evolutions: [16, 17, 18] },
  { code: '19', name: 'Rattata', type: ['Normal'],
  description: 'Will chew on anything with its fangs. If you see one, you can be certain that 40 more live in the area.', 
  category: 'Mouse', abilities: ['Run Away', 'Guts'], gender: 'both', weaknesses: ['Fighting'],
  stats: {hp: 2, attack: 4, defense: 3, specialAttack: 2, specialDefense: 3, speed: 5}, 
  weight: 7.7, height: {ft: 1, in: 0}, evolutions: [19, 20] },
  { code: '20', name: 'Raticate', type: ['Normal'],
  description: 'Its hind feet are webbed. They act as flippers, so it can swim in rivers and hunt for prey.', 
  category: 'Mouse', abilities: ['Run Away', 'Guts'], gender: 'both', weaknesses: ['Fighting'],
  stats: {hp: 4, attack: 5, defense: 4, specialAttack: 3, specialDefense: 5, speed: 6}, 
  weight: 40.8, height: {ft: 2, in: 4}, evolutions: [19, 20] },
  { code: '21', name: 'Spearow', type: ['Normal', 'Flying'],
  description: 'Inept at flying high. However, it can fly around very fast to protect its territory.', 
  category: 'Tiny Bird', abilities: ['Keen Eye'], gender: 'both', weaknesses: ['Electric', 'Ice', 'Rock'],
  stats: {hp: 3, attack: 4, defense: 2, specialAttack: 2, specialDefense: 2, speed: 5}, 
  weight: 4.4, height: {ft: 1, in: 0}, evolutions: [21, 22] },
  { code: '22', name: 'Fearow', type: ['Normal', 'Flying'],
  description: 'A Pokémon that dates back many years. If it senses danger, it flies high and away, instantly.', 
  category: 'Beak', abilities: ['Keen Eye'], gender: 'both', weaknesses: ['Electric', 'Ice', 'Rock'],
  stats: {hp: 4, attack: 6, defense: 4, specialAttack: 4, specialDefense: 4, speed: 6}, 
  weight: 83.8, height: {ft: 3, in: 11}, evolutions: [21, 22] },
  { code: '23', name: 'Ekans', type: ['Poison'],
  description: 'The older it gets, the longer it grows. At night, it wraps its long body around tree branches to rest.', 
  category: 'Snake', abilities: ['Shed Skin', 'Intimidate'], gender: 'both', weaknesses: ['Psychic', 'Ground'],
  stats: {hp: 3, attack: 4, defense: 3, specialAttack: 3, specialDefense: 4, speed: 4}, 
  weight: 15.2, height: {ft: 6, in: 7}, evolutions: [23, 24] },
  { code: '24', name: 'Arbok', type: ['Poison'],
  description: 'The frightening patterns on its belly have been studied. Six variations have been confirmed.', 
  category: 'Cobra', abilities: ['Shed Skin', 'Intimidate'], gender: 'both', weaknesses: ['Psychic', 'Ground'],
  stats: {hp: 4, attack: 6, defense: 5, specialAttack: 4, specialDefense: 5, speed: 5}, 
  weight: 143.3, height: {ft: 11, in: 6}, evolutions: [23, 24] },
  { code: '25', name: 'Pikachu', type: ['Electric'],
  description: 'When it is angered, it immediately discharges the energy stored in the pouches in its cheeks.', 
  category: 'Mouse', abilities: ['Static'], gender: 'both', weaknesses: ['Ground'],
  stats: {hp: 3, attack: 4, defense: 3, specialAttack: 3, specialDefense: 3, speed: 6}, 
  weight: 13.2, height: {ft: 1, in: 4}, evolutions: [172, 25, 26] },
  { code: '26', name: 'Raichu', type: ['Electric'],
  description: 'Its tail discharges electricity into the ground, protecting it from getting shocked.', 
  category: 'Mouse', abilities: ['Static'], gender: 'both', weaknesses: ['Ground'],
  stats: {hp: 4, attack: 6, defense: 4, specialAttack: 6, specialDefense: 5, speed: 7}, 
  weight: 66.1, height: {ft: 2, in: 7}, evolutions: [172, 25, 26] },
  { code: '27', name: 'Sandshrew', type: ['Ground'] },
  { code: '28', name: 'Sandslash', type: ['Ground'] },
  { code: '29', name: 'Nidoran♀', type: ['Poison'] },
  { code: '30', name: 'Nidorina', type: ['Poison'] },
  { code: '31', name: 'Nidoqueen', type: ['Poison', 'Ground'] },
  { code: '32', name: 'Nidoran♂', type: ['Poison'] },
  { code: '33', name: 'Nidorino', type: ['Poison'] },
  { code: '34', name: 'Nidoking', type: ['Poison', 'Ground'] },
  { code: '35', name: 'Clefairy', type: ['Fairy'] },
  { code: '36', name: 'Clefable', type: ['Fairy'] },
  { code: '37', name: 'Vulpix', type: ['Fire'] },
  { code: '38', name: 'Ninetales', type: ['Fire'] },
  { code: '39', name: 'Jigglypuff', type: ['Normal', 'Fairy'] },
  { code: '40', name: 'Wigglytuff', type: ['Normal', 'Fairy'] },
  { code: '41', name: 'Zubat', type: ['Poison', 'Flying'] },
  { code: '42', name: 'Golbat', type: ['Poison', 'Flying'] },
  { code: '43', name: 'Oddish', type: ['Grass', 'Poison'] },
  { code: '44', name: 'Gloom', type: ['Grass', 'Poison'] },
  { code: '45', name: 'Vileplume', type: ['Grass', 'Poison'] },
  { code: '46', name: 'Paras', type: ['Bug', 'Grass'] },
  { code: '47', name: 'Parasect', type: ['Bug', 'Grass'] },
  { code: '48', name: 'Venonat', type: ['Bug', 'Poison'] },
  { code: '49', name: 'Venomoth', type: ['Bug', 'Poison'] },
  { code: '50', name: 'Diglett', type: ['Ground'] },
  { code: '51', name: 'Dugtrio', type: ['Ground'] },
  { code: '52', name: 'Meowth', type: ['Normal'] },
  { code: '53', name: 'Persian', type: ['Normal'] },
  { code: '54', name: 'Psyduck', type: ['Water'] },
  { code: '55', name: 'Golduck', type: ['Water'] },
  { code: '56', name: 'Mankey', type: ['Fighting'] },
  { code: '57', name: 'Primeape', type: ['Fighting'] },
  { code: '58', name: 'Growlithe', type: ['Fire'] },
  { code: '59', name: 'Arcanine', type: ['Fire'] },
  { code: '60', name: 'Poliwag', type: ['Water'] },
  { code: '61', name: 'Poliwhirl', type: ['Water'] },
  { code: '62', name: 'Poliwrath', type: ['Water', 'Fighting'] },
  { code: '63', name: 'Abra', type: ['Psychic'] },
  { code: '64', name: 'Kadabra', type: ['Psychic'] },
  { code: '65', name: 'Alakazam', type: ['Psychic'] },
  { code: '66', name: 'Machop', type: ['Fighting'] },
  { code: '67', name: 'Machoke', type: ['Fighting'] },
  { code: '68', name: 'Machamp', type: ['Fighting'] },
  { code: '69', name: 'Bellsprout', type: ['Grass', 'Poison'] },
  { code: '70', name: 'Weepinbell', type: ['Grass', 'Poison'] },
  { code: '71', name: 'Victreebel', type: ['Grass', 'Poison'] },
  { code: '72', name: 'Tentacool', type: ['Water', 'Poison'] },
  { code: '73', name: 'Tentacruel', type: ['Water', 'Poison'] },
  { code: '74', name: 'Geodude', type: ['Rock', 'Ground'] },
  { code: '75', name: 'Graveler', type: ['Rock', 'Ground'] },
  { code: '76', name: 'Golem', type: ['Rock', 'Ground'] },
  { code: '77', name: 'Ponyta', type: ['Fire'] },
  { code: '78', name: 'Rapidash', type: ['Fire'] },
  { code: '79', name: 'Slowpoke', type: ['Water', 'Psychic'] },
  { code: '80', name: 'Slowbro', type: ['Water', 'Psychic'] },
  { code: '81', name: 'Magnemite', type: ['Electric', 'Steel'] },
  { code: '82', name: 'Magneton', type: ['Electric', 'Steel'] },
  { code: '83', name: 'Farfetch\'d', type: ['Normal', 'Flying'] },
  { code: '84', name: 'Doduo', type: ['Normal', 'Flying'] },
  { code: '85', name: 'Dodrio', type: ['Normal', 'Flying'] },
  { code: '86', name: 'Seel', type: ['Water'] },
  { code: '87', name: 'Dewgong', type: ['Water', 'Ice'] },
  { code: '88', name: 'Grimer', type: ['Poison'] },
  { code: '89', name: 'Muk', type: ['Poison'] },
  { code: '90', name: 'Shellder', type: ['Water'] },
  { code: '91', name: 'Cloyster', type: ['Water', 'Ice'] },
  { code: '92', name: 'Gastly', type: ['Ghost', 'Poison'] },
  { code: '93', name: 'Haunter', type: ['Ghost', 'Poison'] },
  { code: '94', name: 'Gengar', type: ['Ghost', 'Poison'] },
  { code: '95', name: 'Onix', type: ['Rock', 'Ground'] },
  { code: '96', name: 'Drowzee', type: ['Psychic'] },
  { code: '97', name: 'Hypno', type: ['Psychic'] },
  { code: '98', name: 'Krabby', type: ['Water'] },
  { code: '99', name: 'Kingler', type: ['Water'] },
  { code: '100', name: 'Voltorb', type: ['Electric'] },
  { code: '101', name: 'Electrode', type: ['Electric'] },
  { code: '102', name: 'Exeggcute', type: ['Grass', 'Psychic'] },
  { code: '103', name: 'Exeggutor', type: ['Grass', 'Psychic'] },
  { code: '104', name: 'Cubone', type: ['Ground'] },
  { code: '105', name: 'Marowak', type: ['Ground'] },
  { code: '106', name: 'Hitmonlee', type: ['Fighting'] },
  { code: '107', name: 'Hitmonchan', type: ['Fighting'] },
  { code: '108', name: 'Lickitung', type: ['Normal'] },
  { code: '109', name: 'Koffing', type: ['Poison'] },
  { code: '110', name: 'Weezing', type: ['Poison'] },
  { code: '111', name: 'Rhyhorn', type: ['Ground', 'Rock'] },
  { code: '112', name: 'Rhydon', type: ['Ground', 'Rock'] },
  { code: '113', name: 'Chansey', type: ['Normal'] },
  { code: '114', name: 'Tangela', type: ['Grass'] },
  { code: '115', name: 'Kangaskhan', type: ['Normal'] },
  { code: '116', name: 'Horsea', type: ['Water'] },
  { code: '117', name: 'Seadra', type: ['Water'] },
  { code: '118', name: 'Goldeen', type: ['Water'] },
  { code: '119', name: 'Seaking', type: ['Water'] },
  { code: '120', name: 'Staryu', type: ['Water'] },
  { code: '121', name: 'Starmie', type: ['Water', 'Psychic'] },
  { code: '122', name: 'Mr. Mime', type: ['Psychic', 'Fairy'] },
  { code: '123', name: 'Scyther', type: ['Bug', 'Flying'] },
  { code: '124', name: 'Jynx', type: ['Ice', 'Psychic'] },
  { code: '125', name: 'Electabuzz', type: ['Electric'] },
  { code: '126', name: 'Magmar', type: ['Fire'] },
  { code: '127', name: 'Pinsir', type: ['Bug'] },
  { code: '128', name: 'Tauros', type: ['Normal'] },
  { code: '129', name: 'Magikarp', type: ['Water'] },
  { code: '130', name: 'Gyarados', type: ['Water', 'Flying'] },
  { code: '131', name: 'Lapras', type: ['Water', 'Ice'] },
  { code: '132', name: 'Ditto', type: ['Normal'] },
  { code: '133', name: 'Eevee', type: ['Normal'] },
  { code: '134', name: 'Vaporeon', type: ['Water'] },
  { code: '135', name: 'Jolteon', type: ['Electric'] },
  { code: '136', name: 'Flareon', type: ['Fire'] },
  { code: '137', name: 'Porygon', type: ['Normal'] },
  { code: '138', name: 'Omanyte', type: ['Rock', 'Water'] },
  { code: '139', name: 'Omastar', type: ['Rock', 'Water'] },
  { code: '140', name: 'Kabuto', type: ['Rock', 'Water'] },
  { code: '141', name: 'Kabutops', type: ['Rock', 'Water'] },
  { code: '142', name: 'Aerodactyl', type: ['Rock', 'Flying'] },
  { code: '143', name: 'Snorlax', type: ['Normal'] },
  { code: '144', name: 'Articuno', type: ['Ice', 'Flying'] },
  { code: '145', name: 'Zapdos', type: ['Electric', 'Flying'] },
  { code: '146', name: 'Moltres', type: ['Fire', 'Flying'] },
  { code: '147', name: 'Dratini', type: ['Dragon'] },
  { code: '148', name: 'Dragonair', type: ['Dragon'] },
  { code: '149', name: 'Dragonite', type: ['Dragon', 'Flying'] },
  { code: '150', name: 'Mewtwo', type: ['Psychic'] },
  { code: '151', name: 'Mew', type: ['Psychic'] },
  { code: '152', name: 'Chikorita', type: ['Grass'] },
  { code: '153', name: 'Bayleef', type: ['Grass'] },
  { code: '154', name: 'Meganium', type: ['Grass'] },
  { code: '155', name: 'Cyndaquil', type: ['Fire'] },
  { code: '156', name: 'Quilava', type: ['Fire'] },
  { code: '157', name: 'Typhlosion', type: ['Fire'] },
  { code: '158', name: 'Totodile', type: ['Water'] },
  { code: '159', name: 'Croconaw', type: ['Water'] },
  { code: '160', name: 'Feraligatr', type: ['Water'] },
  { code: '161', name: 'Sentret', type: ['Normal'] },
  { code: '162', name: 'Furret', type: ['Normal'] },
  { code: '163', name: 'Hoothoot', type: ['Normal', 'Flying'] },
  { code: '164', name: 'Noctowl', type: ['Normal', 'Flying'] },
  { code: '165', name: 'Ledyba', type: ['Bug', 'Flying'] },
  { code: '166', name: 'Ledian', type: ['Bug', 'Flying'] },
  { code: '167', name: 'Spinarak', type: ['Bug', 'Poison'] },
  { code: '168', name: 'Ariados', type: ['Bug', 'Poison'] },
  { code: '169', name: 'Crobat', type: ['Poison', 'Flying'] },
  { code: '170', name: 'Chinchou', type: ['Water', 'Electric'] },
  { code: '171', name: 'Lanturn', type: ['Water', 'Electric'] },
  { code: '172', name: 'Pichu', type: ['Electric'] },
  { code: '173', name: 'Cleffa', type: ['Fairy'] },
  { code: '174', name: 'Igglybuff', type: ['Normal', 'Fairy'] },
  { code: '175', name: 'Togepi', type: ['Fairy'] },
  { code: '176', name: 'Togetic', type: ['Fairy', 'Flying'] },
  { code: '177', name: 'Natu', type: ['Psychic', 'Flying'] },
  { code: '178', name: 'Xatu', type: ['Psychic', 'Flying'] },
  { code: '179', name: 'Mareep', type: ['Electric'] },
  { code: '180', name: 'Flaaffy', type: ['Electric'] },
  { code: '181', name: 'Ampharos', type: ['Electric'] },
  { code: '182', name: 'Bellossom', type: ['Grass'] },
  { code: '183', name: 'Marill', type: ['Water', 'Fairy'] },
  { code: '184', name: 'Azumarill', type: ['Water', 'Fairy'] },
  { code: '185', name: 'Sudowoodo', type: ['Rock'] },
  { code: '186', name: 'Politoed', type: ['Water'] },
  { code: '187', name: 'Hoppip', type: ['Grass', 'Flying'] },
  { code: '188', name: 'Skiploom', type: ['Grass', 'Flying'] },
  { code: '189', name: 'Jumpluff', type: ['Grass', 'Flying'] },
  { code: '190', name: 'Aipom', type: ['Normal'] },
  { code: '191', name: 'Sunkern', type: ['Grass'] },
  { code: '192', name: 'Sunflora', type: ['Grass'] },
  { code: '193', name: 'Yanma', type: ['Bug', 'Flying'] },
  { code: '194', name: 'Wooper', type: ['Water', 'Ground'] },
  { code: '195', name: 'Quagsire', type: ['Water', 'Ground'] },
  { code: '196', name: 'Espeon', type: ['Psychic'] },
  { code: '197', name: 'Umbreon', type: ['Dark'] },
  { code: '198', name: 'Murkrow', type: ['Dark', 'Flying'] },
  { code: '199', name: 'Slowking', type: ['Water', 'Psychic'] },
  { code: '200', name: 'Misdreavous', type: ['Ghost'] },
  { code: '201', name: 'Unown', type: ['Psychic'] },
  { code: '202', name: 'Wobbuffet', type: ['Psychic'] },
  { code: '203', name: 'Girafarig', type: ['Normal', 'Psychic'] },
  { code: '204', name: 'Pineco', type: ['Bug'] },
  { code: '205', name: 'Forretress', type: ['Bug', 'Steel'] },
  { code: '206', name: 'Dunsparce', type: ['Normal'] },
  { code: '207', name: 'Gligar', type: ['Ground', 'Flying'] },
  { code: '208', name: 'Steelix', type: ['Steel', 'Ground'] },
  { code: '209', name: 'Snubbull', type: ['Fairy'] },
  { code: '210', name: 'Granbull', type: ['Fairy'] },
  { code: '211', name: 'Qwilfish', type: ['Water', 'Poison'] },
  { code: '212', name: 'Scizor', type: ['Bug', 'Steel'] },
  { code: '213', name: 'Shuckle', type: ['Bug', 'Rock'] },
  { code: '214', name: 'Heracross', type: ['Bug', 'Fighting'] },
  { code: '215', name: 'Sneasel', type: ['Dark', 'Ice'] },
  { code: '216', name: 'Teddiursa', type: ['Normal'] },
  { code: '217', name: 'Ursaring', type: ['Normal'] },
  { code: '218', name: 'Slugma', type: ['Fire'] },
  { code: '219', name: 'Magcargo', type: ['Fire', 'Rock'] },
  { code: '220', name: 'Swinub', type: ['Ice', 'Ground'] },
  { code: '221', name: 'Piloswine', type: ['Ice', 'Ground'] },
  { code: '222', name: 'Corsola', type: ['Water', 'Rock'] },
  { code: '223', name: 'Remoraid', type: ['Water'] },
  { code: '224', name: 'Octillery', type: ['Water'] },
  { code: '225', name: 'Delibird', type: ['Ice', 'Flying'] },
  { code: '226', name: 'Mantine', type: ['Water', 'Flying'] },
  { code: '227', name: 'Skarmory', type: ['Steel', 'Flying'] },
  { code: '228', name: 'Houndour', type: ['Dark', 'Fire'] },
  { code: '229', name: 'Houndoom', type: ['Dark', 'Fire'] },
  { code: '230', name: 'Kingdra', type: ['Water', 'Dragon'] },
  { code: '231', name: 'Phanpy', type: ['Ground'] },
  { code: '232', name: 'Donphan', type: ['Ground'] },
  { code: '233', name: 'Porygon2', type: ['Normal'] },
  { code: '234', name: 'Stantler', type: ['Normal'] },
  { code: '235', name: 'Smeargle', type: ['Normal'] },
  { code: '236', name: 'Tyrogue', type: ['Fighting'] },
  { code: '237', name: 'Hitmontop', type: ['Fighting'] },
  { code: '238', name: 'Smoochum', type: ['Ice', 'Psychic'] },
  { code: '239', name: 'Elekid', type: ['Electric'] },
  { code: '240', name: 'Magby', type: ['Fire'] },
  { code: '241', name: 'Miltank', type: ['Normal'] },
  { code: '242', name: 'Blissey', type: ['Normal'] },
  { code: '243', name: 'Raikou', type: ['Electric'] },
  { code: '244', name: 'Entei', type: ['Fire'] },
  { code: '245', name: 'Suicune', type: ['Water'] },
  { code: '246', name: 'Larvitar', type: ['Rock', 'Ground'] },
  { code: '247', name: 'Pupitar', type: ['Rock', 'Ground'] },
  { code: '248', name: 'Tyranitar', type: ['Rock', 'Dark'] },
  { code: '249', name: 'Lugia', type: ['Psychic', 'Flying'] },
  { code: '250', name: 'Ho-Oh', type: ['Fire', 'Flying'] },
  { code: '251', name: 'Celebi', type: ['Psychic', 'Grass'] },
  { code: '252', name: 'Treecko', type: ['Grass'] },
  { code: '253', name: 'Grovyle', type: ['Grass'] },
  { code: '254', name: 'Sceptile', type: ['Grass'] },
  { code: '255', name: 'Torchic', type: ['Fire'] },
  { code: '256', name: 'Combusken', type: ['Fire', 'Fighting'] },
  { code: '257', name: 'Blaziken', type: ['Fire', 'Fighting'] },
  { code: '258', name: 'Mudkip', type: ['Water'] },
  { code: '259', name: 'Marshtomp', type: ['Water', 'Ground'] },
  { code: '260', name: 'Swampert', type: ['Water', 'Ground'] },
  { code: '261', name: 'Poochyena', type: ['Dark'] },
  { code: '262', name: 'Mightyena', type: ['Dark'] },
  { code: '263', name: 'Zigzagoon', type: ['Normal'] },
  { code: '264', name: 'Linoone', type: ['Normal'] },
  { code: '265', name: 'Wurmple', type: ['Bug'] },
  { code: '266', name: 'Silcoon', type: ['Bug'] },
  { code: '267', name: 'Beautifly', type: ['Bug', 'Flying'] },
  { code: '268', name: 'Cascoon', type: ['Bug'] },
  { code: '269', name: 'Dustox', type: ['Bug', 'Poison'] },
  { code: '270', name: 'Lotad', type: ['Water', 'Grass'] },
  { code: '271', name: 'Lombre', type: ['Water', 'Grass'] },
  { code: '272', name: 'Ludicolo', type: ['Water', 'Grass'] },
  { code: '273', name: 'Seedot', type: ['Grass'] },
  { code: '274', name: 'Nuzleaf', type: ['Grass', 'Dark'] },
  { code: '275', name: 'Shiftry', type: ['Grass', 'Dark'] },
  { code: '276', name: 'Taillow', type: ['Normal', 'Flying'] },
  { code: '277', name: 'Swellow', type: ['Normal', 'Flying'] },
  { code: '278', name: 'Wingull', type: ['Water', 'Flying'] },
  { code: '279', name: 'Pelipper', type: ['Water', 'Flying'] },
  { code: '280', name: 'Ralts', type: ['Psychic', 'Fairy'] },
  { code: '281', name: 'Kirlia', type: ['Psychic', 'Fairy'] },
  { code: '282', name: 'Gardevoir', type: ['Psychic', 'Fairy'] },
  { code: '283', name: 'Surskit', type: ['Bug', 'Water'] },
  { code: '284', name: 'Masquerain', type: ['Bug', 'Flying'] },
  { code: '285', name: 'Shroomish', type: ['Grass'] },
  { code: '286', name: 'Breloom', type: ['Grass', 'Fighting'] },
  { code: '287', name: 'Slakoth', type: ['Normal'] },
  { code: '288', name: 'Vigoroth', type: ['Normal'] },
  { code: '289', name: 'Slaking', type: ['Normal'] },
  { code: '290', name: 'Nincada', type: ['Bug', 'Ground'] },
  { code: '291', name: 'Ninjask', type: ['Bug', 'Flying'] },
  { code: '292', name: 'Shedinja', type: ['Bug', 'Ghost'] },
  { code: '293', name: 'Whismur', type: ['Normal'] },
  { code: '294', name: 'Loudred', type: ['Normal'] },
  { code: '295', name: 'Exploud', type: ['Normal'] },
  { code: '296', name: 'Makuhita', type: ['Fighting'] },
  { code: '297', name: 'Hariyama', type: ['Fighting'] },
  { code: '298', name: 'Azurill', type: ['Normal', 'Fairy'] },
  { code: '299', name: 'Nosepass', type: ['Rock'] },
  { code: '300', name: 'Skitty', type: ['Normal'] },
  { code: '301', name: 'Delcatty', type: ['Normal'] },
  { code: '302', name: 'Sableye', type: ['Dark', 'Ghost'] },
  { code: '303', name: 'Mawile', type: ['Steel', 'Fairy'] },
  { code: '304', name: 'Aron', type: ['Steel', 'Rock'] },
  { code: '305', name: 'Lairon', type: ['Steel', 'Rock'] },
  { code: '306', name: 'Aggron', type: ['Steel', 'Rock'] },
  { code: '307', name: 'Meditite', type: ['Fighting', 'Psychic'] },
  { code: '308', name: 'Medicham', type: ['Fighting', 'Psychic'] },
  { code: '309', name: 'Electrike', type: ['Electric'] },
  { code: '310', name: 'Manectric', type: ['Electric'] },
  { code: '311', name: 'Plusle', type: ['Electric'] },
  { code: '312', name: 'Minun', type: ['Electric'] },
  { code: '313', name: 'Volbeat', type: ['Bug'] },
  { code: '314', name: 'Illumise', type: ['Bug'] },
  { code: '315', name: 'Roselia', type: ['Grass', 'Poison'] },
  { code: '316', name: 'Gulpin', type: ['Poison'] },
  { code: '317', name: 'Swalot', type: ['Poison'] },
  { code: '318', name: 'Carvanha', type: ['Water', 'Dark'] },
  { code: '319', name: 'Sharpedo', type: ['Water', 'Dark'] },
  { code: '320', name: 'Wailmer', type: ['Water'] },
  { code: '321', name: 'Wailord', type: ['Water'] },
  { code: '322', name: 'Numel', type: ['Fire', 'Ground'] },
  { code: '323', name: 'Camerupt', type: ['Fire', 'Ground'] },
  { code: '324', name: 'Torkoal', type: ['Fire'] },
  { code: '325', name: 'Spoink', type: ['Psychic'] },
  { code: '326', name: 'Grumpig', type: ['Psychic'] },
  { code: '327', name: 'Spinda', type: ['Normal'] },
  { code: '328', name: 'Trapinch', type: ['Ground'] },
  { code: '329', name: 'Vibrava', type: ['Ground', 'Dragon'] },
  { code: '330', name: 'Flygon', type: ['Ground', 'Dragon'] },
  { code: '331', name: 'Cacnea', type: ['Grass'] },
  { code: '332', name: 'Cacturne', type: ['Grass', 'Dark'] },
  { code: '333', name: 'Swablu', type: ['Normal', 'Flying'] },
  { code: '334', name: 'Altaria', type: ['Dragon', 'Flying'] },
  { code: '335', name: 'Zangoose', type: ['Normal'] },
  { code: '336', name: 'Seviper', type: ['Poison'] },
  { code: '337', name: 'Lunatone', type: ['Rock', 'Psychic'] },
  { code: '338', name: 'Solrock', type: ['Rock', 'Psychic'] },
  { code: '339', name: 'Barboach', type: ['Water', 'Ground'] },
  { code: '340', name: 'Whiscash', type: ['Water', 'Ground'] },
  { code: '341', name: 'Corphish', type: ['Water'] },
  { code: '342', name: 'Crawdaunt', type: ['Water', 'Dark'] },
  { code: '343', name: 'Baltoy', type: ['Ground', 'Psychic'] },
  { code: '344', name: 'Claydol', type: ['Ground', 'Psychic'] },
  { code: '345', name: 'Lileep', type: ['Rock', 'Grass'] },
  { code: '346', name: 'Cradily', type: ['Rock', 'Grass'] },
  { code: '347', name: 'Anorith', type: ['Rock', 'Bug'] },
  { code: '348', name: 'Armaldo', type: ['Rock', 'Bug'] },
  { code: '349', name: 'Feebas', type: ['Water'] },
  { code: '350', name: 'Milotic', type: ['Water'] },
  { code: '351', name: 'Castform', type: ['Normal'] },
  { code: '352', name: 'Kecleon', type: ['Normal'] },
  { code: '353', name: 'Shuppet', type: ['Ghost'] },
  { code: '354', name: 'Banette', type: ['Ghost'] },
  { code: '355', name: 'Duskull', type: ['Ghost'] },
  { code: '356', name: 'Dusclops', type: ['Ghost'] },
  { code: '357', name: 'Tropius', type: ['Grass', 'Flying'] },
  { code: '358', name: 'Chimecho', type: ['Psychic'] },
  { code: '359', name: 'Absol', type: ['Dark'] },
  { code: '360', name: 'Wynaut', type: ['Psychic'] },
  { code: '361', name: 'Snorunt', type: ['Ice'] },
  { code: '362', name: 'Glalie', type: ['Ice'] },
  { code: '363', name: 'Spheal', type: ['Ice', 'Water'] },
  { code: '364', name: 'Sealeo', type: ['Ice', 'Water'] },
  { code: '365', name: 'Walrein', type: ['Ice', 'Water'] },
  { code: '366', name: 'Clamperl', type: ['Water'] },
  { code: '367', name: 'Huntail', type: ['Water'] },
  { code: '368', name: 'Gorebyss', type: ['Water'] },
  { code: '369', name: 'Relicanth', type: ['Water', 'Rock'] },
  { code: '370', name: 'Luvdisc', type: ['Water'] },
  { code: '371', name: 'Bagon', type: ['Dragon'] },
  { code: '372', name: 'Shelgon', type: ['Dragon'] },
  { code: '373', name: 'Salamence', type: ['Dragon', 'Flying'] },
  { code: '374', name: 'Beldum', type: ['Steel', 'Psychic'] },
  { code: '375', name: 'Metang', type: ['Steel', 'Psychic'] },
  { code: '376', name: 'Metagross', type: ['Steel', 'Psychic'] },
  { code: '377', name: 'Regirock', type: ['Rock'] },
  { code: '378', name: 'Regice', type: ['Ice'] },
  { code: '379', name: 'Registeel', type: ['Steel'] },
  { code: '380', name: 'Latias', type: ['Dragon', 'Psychic'] },
  { code: '381', name: 'Latios', type: ['Dragon', 'Psychic'] },
  { code: '382', name: 'Kyogre', type: ['Water'] },
  { code: '383', name: 'Groudon', type: ['Ground'] },
  { code: '384', name: 'Rayquaza', type: ['Dragon', 'Flying'] },
  { code: '385', name: 'Jirachi', type: ['Steel', 'Psychic'] },
  { code: '386', name: 'Deoxys', type: ['Psychic'] },
  { code: '387', name: 'Turtwig', type: ['Grass'] },
  { code: '388', name: 'Grotle', type: ['Grass'] },
  { code: '389', name: 'Torterra', type: ['Grass', 'Ground'] },
  { code: '390', name: 'Chimchar', type: ['Fire'] },
  { code: '391', name: 'Monferno', type: ['Fire', 'Fighting'] },
  { code: '392', name: 'Infernape', type: ['Fire', 'Fighting'] },
  { code: '393', name: 'Piplup', type: ['Water'] },
  { code: '394', name: 'Prinplup', type: ['Water'] },
  { code: '395', name: 'Empoleon', type: ['Water', 'Steel'] },
  { code: '396', name: 'Starly', type: ['Normal', 'Flying'] },
  { code: '397', name: 'Staravia', type: ['Normal', 'Flying'] },
  { code: '398', name: 'Staraptor', type: ['Normal', 'Flying'] },
  { code: '399', name: 'Bidoof', type: ['Normal'] },
  { code: '400', name: 'Bibarel', type: ['Normal', 'Water'] },
  { code: '401', name: 'Kricketot', type: ['Bug'] },
  { code: '402', name: 'Kricketune', type: ['Bug'] },
  { code: '403', name: 'Shinx', type: ['Electric'] },
  { code: '404', name: 'Luxio', type: ['Electric'] },
  { code: '405', name: 'Luxray', type: ['Electric'] },
  { code: '406', name: 'Budew', type: ['Grass', 'Poison'] },
  { code: '407', name: 'Roserade', type: ['Grass', 'Poison'] },
  { code: '408', name: 'Cranidos', type: ['Rock'] },
  { code: '409', name: 'Rampardos', type: ['Rock'] },
  { code: '410', name: 'Shieldon', type: ['Rock', 'Steel'] },
  { code: '411', name: 'Bastiodon', type: ['Rock', 'Steel'] },
  { code: '412', name: 'Burmy', type: ['Bug'] },
  { code: '413', name: 'Wormadam', type: ['Bug', 'Grass'] },
  { code: '414', name: 'Mothim', type: ['Bug', 'Flying'] },
  { code: '415', name: 'Combee', type: ['Bug', 'Flying'] },
  { code: '416', name: 'Vespiquen', type: ['Bug', 'Flying'] },
  { code: '417', name: 'Pachirisu', type: ['Electric'] },
  { code: '418', name: 'Buizel', type: ['Water'] },
  { code: '419', name: 'Floatzel', type: ['Water'] },
  { code: '420', name: 'Cherubi', type: ['Grass'] },
  { code: '421', name: 'Cherrim', type: ['Grass'] },
  { code: '422', name: 'Shellos', type: ['Water'] },
  { code: '423', name: 'Gastrodon', type: ['Water', 'Ground'] },
  { code: '424', name: 'Ambipom', type: ['Normal'] },
  { code: '425', name: 'Drifloon', type: ['Ghost', 'Flying'] },
  { code: '426', name: 'Drifblim', type: ['Ghost', 'Flying'] },
  { code: '427', name: 'Buneary', type: ['Normal'] },
  { code: '428', name: 'Lopunny', type: ['Normal'] },
  { code: '429', name: 'Mismagius', type: ['Ghost'] },
  { code: '430', name: 'Honchkrow', type: ['Dark', 'Flying'] },
  { code: '431', name: 'Glameow', type: ['Normal'] },
  { code: '432', name: 'Purugly', type: ['Normal'] },
  { code: '433', name: 'Chingling', type: ['Psychic'] },
  { code: '434', name: 'Stunky', type: ['Poison', 'Dark'] },
  { code: '435', name: 'Skuntank', type: ['Poison', 'Dark'] },
  { code: '436', name: 'Bronzor', type: ['Steel', 'Psychic'] },
  { code: '437', name: 'Bronzong', type: ['Steel', 'Psychic'] },
  { code: '438', name: 'Bonsly', type: ['Rock'] },
  { code: '439', name: 'Mime Jr.', type: ['Psychic', 'Fairy'] },
  { code: '440', name: 'Happiny', type: ['Normal'] },
  { code: '441', name: 'Chatot', type: ['Normal', 'Flying'] },
  { code: '442', name: 'Spiritomb', type: ['Ghost', 'Dark'] },
  { code: '443', name: 'Gible', type: ['Dragon', 'Ground'] },
  { code: '444', name: 'Gabite', type: ['Dragon', 'Ground'] },
  { code: '445', name: 'Garchomp', type: ['Dragon', 'Ground'] },
  { code: '446', name: 'Munchlax', type: ['Normal'] },
  { code: '447', name: 'Riolu', type: ['Fighting'] },
  { code: '448', name: 'Lucario', type: ['Fighting', 'Steel'] },
  { code: '449', name: 'Hippopotas', type: ['Ground'] },
  { code: '450', name: 'Hippowdon', type: ['Ground'] },
  { code: '451', name: 'Skorupi', type: ['Poison', 'Bug'] },
  { code: '452', name: 'Drapion', type: ['Poison', 'Dark'] },
  { code: '453', name: 'Croagunk', type: ['Poison', 'Fighting'] },
  { code: '454', name: 'Toxicroak', type: ['Poison', 'Fighting'] },
  { code: '455', name: 'Carnivine', type: ['Grass'] },
  { code: '456', name: 'Finneon', type: ['Water'] },
  { code: '457', name: 'Lumineon', type: ['Water'] },
  { code: '458', name: 'Mantyke', type: ['Water', 'Flying'] },
  { code: '459', name: 'Snover', type: ['Grass', 'Ice'] },
  { code: '460', name: 'Abomasnow', type: ['Grass', 'Ice'] },
  { code: '461', name: 'Weavile', type: ['Dark', 'Ice'] },
  { code: '462', name: 'Magnezone', type: ['Electric', 'Steel'] },
  { code: '463', name: 'Lickilicky', type: ['Normal'] },
  { code: '464', name: 'Rhyperior', type: ['Ground', 'Rock'] },
  { code: '465', name: 'Tangrowth', type: ['Grass'] },
  { code: '466', name: 'Electivire', type: ['Electric'] },
  { code: '467', name: 'Magmortar', type: ['Fire'] },
  { code: '468', name: 'Togekiss', type: ['Fairy', 'Flying'] },
  { code: '469', name: 'Yanmega', type: ['Bug', 'Flying'] },
  { code: '470', name: 'Leafeon', type: ['Grass'] },
  { code: '471', name: 'Glaceon', type: ['Ice'] },
  { code: '472', name: 'Gliscor', type: ['Ground', 'Flying'] },
  { code: '473', name: 'Mamoswine', type: ['Ice', 'Ground'] },
  { code: '474', name: 'Porygon-Z', type: ['Normal'] },
  { code: '475', name: 'Gallade', type: ['Psychic', 'Fighting'] },
  { code: '476', name: 'Probopass', type: ['Rock', 'Steel'] },
  { code: '477', name: 'Dusknoir', type: ['Ghost'] },
  { code: '478', name: 'Froslass', type: ['Ice', 'Ghost'] },
  { code: '479', name: 'Rotom', type: ['Electric', 'Ghost'] },
  { code: '480', name: 'Uxie', type: ['Psychic'] },
  { code: '481', name: 'Mesprit', type: ['Psychic'] },
  { code: '482', name: 'Azelf', type: ['Psychic'] },
  { code: '483', name: 'Dialga', type: ['Steel', 'Dragon'] },
  { code: '484', name: 'Palkia', type: ['Water', 'Dragon'] },
  { code: '485', name: 'Heatran', type: ['Fire', 'Steel'] },
  { code: '486', name: 'Regigigas', type: ['Normal'] },
  { code: '487', name: 'Giratina', type: ['Ghost', 'Dragon'] },
  { code: '488', name: 'Cresselia', type: ['Psychic'] },
  { code: '489', name: 'Phione', type: ['Water'] },
  { code: '490', name: 'Manaphy', type: ['Water'] },
  { code: '491', name: 'Darkrai', type: ['Dark'] },
  { code: '492', name: 'Shaymin', type: ['Grass'] },
  { code: '493', name: 'Arceus', type: ['Normal'] },
  { code: '494', name: 'Victini', type: ['Psychic', 'Fire'] },
  { code: '495', name: 'Snivy', type: ['Grass'] },
  { code: '496', name: 'Servine', type: ['Grass'] },
  { code: '497', name: 'Serperior', type: ['Grass'] },
  { code: '498', name: 'Tepig', type: ['Fire'] },
  { code: '499', name: 'Pignite', type: ['Fire', 'Fighting'] },
  { code: '500', name: 'Emboar', type: ['Fire', 'Fighting'] },
  { code: '501', name: 'Oshawott', type: ['Water'] },
  { code: '502', name: 'Dewott', type: ['Water'] },
  { code: '503', name: 'Samurott', type: ['Water'] },
  { code: '504', name: 'Patrat', type: ['Normal'] },
  { code: '505', name: 'Watchog', type: ['Normal'] },
  { code: '506', name: 'Lillipup', type: ['Normal'] },
  { code: '507', name: 'Herdier', type: ['Normal'] },
  { code: '508', name: 'Stoutland', type: ['Normal'] },
  { code: '509', name: 'Purrloin', type: ['Dark'] },
  { code: '510', name: 'Liepard', type: ['Dark'] },
  { code: '511', name: 'Pansage', type: ['Grass'] },
  { code: '512', name: 'Simisage', type: ['Grass'] },
  { code: '513', name: 'Pansear', type: ['Fire'] },
  { code: '514', name: 'Simisear', type: ['Fire'] },
  { code: '515', name: 'Panpour', type: ['Water'] },
  { code: '516', name: 'Simipour', type: ['Water'] },
  { code: '517', name: 'Munna', type: ['Psychic'] },
  { code: '518', name: 'Musharna', type: ['Psychic'] },
  { code: '519', name: 'Pidove', type: ['Normal', 'Flying'] },
  { code: '520', name: 'Tranquill', type: ['Normal', 'Flying'] },
  { code: '521', name: 'Unfezant', type: ['Normal', 'Flying'] },
  { code: '522', name: 'Blitzle', type: ['Electric'] },
  { code: '523', name: 'Zebstrika', type: ['Electric'] },
  { code: '524', name: 'Roggenrola', type: ['Rock'] },
  { code: '525', name: 'Boldore', type: ['Rock'] },
  { code: '526', name: 'Gigalith', type: ['Rock'] },
  { code: '527', name: 'Woobat', type: ['Psychic', 'Flying'] },
  { code: '528', name: 'Swoobat', type: ['Psychic', 'Flying'] },
  { code: '529', name: 'Drilbur', type: ['Ground'] },
  { code: '530', name: 'Excadrill', type: ['Ground', 'Steel'] },
  { code: '531', name: 'Audino', type: ['Normal'] },
  { code: '532', name: 'Timburr', type: ['Fighting'] },
  { code: '533', name: 'Gurdurr', type: ['Fighting'] },
  { code: '534', name: 'Conkeldurr', type: ['Fighting'] },
  { code: '535', name: 'Tympole', type: ['Water'] },
  { code: '536', name: 'Palpitoad', type: ['Water', 'Ground'] },
  { code: '537', name: 'Seismitoad', type: ['Water', 'Ground'] },
  { code: '538', name: 'Throh', type: ['Fighting'] },
  { code: '539', name: 'Sawk', type: ['Fighting'] },
  { code: '540', name: 'Sewaddle', type: ['Bug', 'Grass'] },
  { code: '541', name: 'Swadloon', type: ['Bug', 'Grass'] },
  { code: '542', name: 'Leavanny', type: ['Bug', 'Grass'] },
  { code: '543', name: 'Venipede', type: ['Bug', 'Poison'] },
  { code: '544', name: 'Whirlipede', type: ['Bug', 'Poison'] },
  { code: '545', name: 'Scolipede', type: ['Bug', 'Poison'] },
  { code: '546', name: 'Cottonee', type: ['Grass', 'Fairy'] },
  { code: '547', name: 'Whimsicott', type: ['Grass', 'Fairy'] },
  { code: '548', name: 'Petilil', type: ['Grass'] },
  { code: '549', name: 'Lilligant', type: ['Grass'] },
  { code: '550', name: 'Basculin', type: ['Water'] },
  { code: '551', name: 'Sandile', type: ['Ground', 'Dark'] },
  { code: '552', name: 'Krokorok', type: ['Ground', 'Dark'] },
  { code: '553', name: 'Krookodile', type: ['Ground', 'Dark'] },
  { code: '554', name: 'Darumaka', type: ['Fire'] },
  { code: '555', name: 'Darmanitan', type: ['Fire'] },
  { code: '556', name: 'Maractus', type: ['Grass'] },
  { code: '557', name: 'Dwebble', type: ['Bug', 'Rock'] },
  { code: '558', name: 'Crustle', type: ['Bug', 'Rock'] },
  { code: '559', name: 'Scraggy', type: ['Dark', 'Fighting'] },
  { code: '560', name: 'Scrafty', type: ['Dark', 'Fighting'] },
  { code: '561', name: 'Sigilyph', type: ['Psychic', 'Flying'] },
  { code: '562', name: 'Yamask', type: ['Ghost'] },
  { code: '563', name: 'Cofagrigus', type: ['Ghost'] },
  { code: '564', name: 'Tirtouga', type: ['Water', 'Rock'] },
  { code: '565', name: 'Carracosta', type: ['Water', 'Rock'] },
  { code: '566', name: 'Archen', type: ['Rock', 'Flying'] },
  { code: '567', name: 'Archeops', type: ['Rock', 'Flying'] },
  { code: '568', name: 'Trubbish', type: ['Poison'] },
  { code: '569', name: 'Garbodor', type: ['Poison'] },
  { code: '570', name: 'Zorua', type: ['Dark'] },
  { code: '571', name: 'Zoroark', type: ['Dark'] },
  { code: '572', name: 'Minccino', type: ['Normal'] },
  { code: '573', name: 'Cinccino', type: ['Normal'] },
  { code: '574', name: 'Gothita', type: ['Psychic'] },
  { code: '575', name: 'Gothorita', type: ['Psychic'] },
  { code: '576', name: 'Gothitelle', type: ['Psychic'] },
  { code: '577', name: 'Solosis', type: ['Psychic'] },
  { code: '578', name: 'Duosion', type: ['Psychic'] },
  { code: '579', name: 'Reuniclus', type: ['Psychic'] },
  { code: '580', name: 'Ducklett', type: ['Water', 'Flying'] },
  { code: '581', name: 'Swanna', type: ['Water', 'Flying'] },
  { code: '582', name: 'Vanillite', type: ['Ice'] },
  { code: '583', name: 'Vanillish', type: ['Ice'] },
  { code: '584', name: 'Vanilluxe', type: ['Ice'] },
  { code: '585', name: 'Deerling', type: ['Normal', 'Grass'] },
  { code: '586', name: 'Sawsbuck', type: ['Normal', 'Grass'] },
  { code: '587', name: 'Emolga', type: ['Electric', 'Flying'] },
  { code: '588', name: 'Karrablast', type: ['Bug'] },
  { code: '589', name: 'Escavalier', type: ['Bug', 'Steel'] },
  { code: '590', name: 'Foongus', type: ['Grass', 'Poison'] },
  { code: '591', name: 'Amoonguss', type: ['Grass', 'Poison'] },
  { code: '592', name: 'Frillish', type: ['Water', 'Ghost'] },
  { code: '593', name: 'Jellicent', type: ['Water', 'Ghost'] },
  { code: '594', name: 'Alomomola', type: ['Water'] },
  { code: '595', name: 'Joltik', type: ['Bug', 'Electric'] },
  { code: '596', name: 'Galvantula', type: ['Bug', 'Electric'] },
  { code: '597', name: 'Ferroseed', type: ['Grass', 'Steel'] },
  { code: '598', name: 'Ferrothorn', type: ['Grass', 'Steel'] },
  { code: '599', name: 'Klink', type: ['Steel'] },
  { code: '600', name: 'Klang', type: ['Steel'] },
  { code: '601', name: 'Klinklang', type: ['Steel'] },
  { code: '602', name: 'Tynamo', type: ['Electric'] },
  { code: '603', name: 'Eelektrik', type: ['Electric'] },
  { code: '604', name: 'Eelektross', type: ['Electric'] },
  { code: '605', name: 'Elgyem', type: ['Psychic'] },
  { code: '606', name: 'Beheeyem', type: ['Psychic'] },
  { code: '607', name: 'Litwick', type: ['Ghost', 'Fire'] },
  { code: '608', name: 'Lampent', type: ['Ghost', 'Fire'] },
  { code: '609', name: 'Chandelure', type: ['Ghost', 'Fire'] },
  { code: '610', name: 'Axew', type: ['Dragon'] },
  { code: '611', name: 'Fraxure', type: ['Dragon'] },
  { code: '612', name: 'Haxorus', type: ['Dragon'] },
  { code: '613', name: 'Cubchoo', type: ['Ice'] },
  { code: '614', name: 'Beartic', type: ['Ice'] },
  { code: '615', name: 'Cryogonal', type: ['Ice'] },
  { code: '616', name: 'Shelmet', type: ['Bug'] },
  { code: '617', name: 'Accelgor', type: ['Bug'] },
  { code: '618', name: 'Stunfisk', type: ['Ground', 'Electric'] },
  { code: '619', name: 'Mienfoo', type: ['Fighting'] },
  { code: '620', name: 'Mienshao', type: ['Fighting'] },
  { code: '621', name: 'Druddigon', type: ['Dragon'] },
  { code: '622', name: 'Golett', type: ['Ground', 'Ghost'] },
  { code: '623', name: 'Golurk', type: ['Ground', 'Ghost'] },
  { code: '624', name: 'Pawniard', type: ['Dark', 'Steel'] },
  { code: '625', name: 'Bisharp', type: ['Dark', 'Steel'] },
  { code: '626', name: 'Bouffalant', type: ['Normal'] },
  { code: '627', name: 'Rufflet', type: ['Normal', 'Flying'] },
  { code: '628', name: 'Braviary', type: ['Normal', 'Flying'] },
  { code: '629', name: 'Vullaby', type: ['Dark', 'Flying'] },
  { code: '630', name: 'Mandibuzz', type: ['Dark', 'Flying'] },
  { code: '631', name: 'Heatmor', type: ['Fire'] },
  { code: '632', name: 'Durant', type: ['Bug', 'Steel'] },
  { code: '633', name: 'Deino', type: ['Dark', 'Dragon'] },
  { code: '634', name: 'Zweilous', type: ['Dark', 'Dragon'] },
  { code: '635', name: 'Hydreigon', type: ['Dark', 'Dragon'] },
  { code: '636', name: 'Larvesta', type: ['Bug', 'Fire'] },
  { code: '637', name: 'Volcarona', type: ['Bug', 'Fire'] },
  { code: '638', name: 'Cobalion', type: ['Steel', 'Fighting'] },
  { code: '639', name: 'Terrakion', type: ['Rock', 'Fighting'] },
  { code: '640', name: 'Virizion', type: ['Grass', 'Fighting'] },
  { code: '641', name: 'Tornadus', type: ['Flying'] },
  { code: '642', name: 'Thundurus', type: ['Electric', 'Flying'] },
  { code: '643', name: 'Reshiram', type: ['Dragon', 'Fire'] },
  { code: '644', name: 'Zekrom', type: ['Dragon', 'Electric'] },
  { code: '645', name: 'Landorus', type: ['Ground', 'Flying'] },
  { code: '646', name: 'Kyurem', type: ['Dragon', 'Ice'] },
  { code: '647', name: 'Keldeo', type: ['Water', 'Fighting'] },
  { code: '648', name: 'Meloetta', type: ['Normal', 'Psychic'] },
  { code: '649', name: 'Genesect', type: ['Bug', 'Steel'] },
  { code: '650', name: 'Chespin', type: ['Grass'] },
  { code: '651', name: 'Quilladin', type: ['Grass'] },
  { code: '652', name: 'Chesnaught', type: ['Grass', 'Fighting'] },
  { code: '653', name: 'Fennekin', type: ['Fire'] },
  { code: '654', name: 'Braixen', type: ['Fire', 'Psychic'] },
  { code: '655', name: 'Delphox', type: ['Fire', 'Psychic'] },
  { code: '656', name: 'Froakie', type: ['Water'] },
  { code: '657', name: 'Frogadier', type: ['Water'] },
  { code: '658', name: 'Greninja', type: ['Water', 'Dark'] },
  { code: '659', name: 'Bunnelby', type: ['Normal'] },
  { code: '660', name: 'Diggersby', type: ['Normal', 'Ground'] },
  { code: '661', name: 'Fletchling', type: ['Normal', 'Flying'] },
  { code: '662', name: 'Fletchinder', type: ['Fire', 'Flying'] },
  { code: '663', name: 'Talonflame', type: ['Fire', 'Flying'] },
  { code: '664', name: 'Scatterbug', type: ['Bug'] },
  { code: '665', name: 'Spewpa', type: ['Bug'] },
  { code: '666', name: 'Vivillon', type: ['Bug', 'Flying'] },
  { code: '667', name: 'Litleo', type: ['Fire', 'Normal'] },
  { code: '668', name: 'Pyroar', type: ['Fire', 'Normal'] },
  { code: '669', name: 'Flabébé', type: ['Fairy'] },
  { code: '670', name: 'Floette', type: ['Fairy'] },
  { code: '671', name: 'Florges', type: ['Fairy'] },
  { code: '672', name: 'Skiddo', type: ['Grass'] },
  { code: '673', name: 'Gogoat', type: ['Grass'] },
  { code: '674', name: 'Pancham', type: ['Fighting'] },
  { code: '675', name: 'Pangoro', type: ['Fighting', 'Dark'] },
  { code: '676', name: 'Furfrou', type: ['Normal'] },
  { code: '677', name: 'Espurr', type: ['Psychic'] },
  { code: '678', name: 'Meowstic', type: ['Psychic'] },
  { code: '679', name: 'Honedge', type: ['Steel', 'Ghost'] },
  { code: '680', name: 'Doublade', type: ['Steel', 'Ghost'] },
  { code: '681', name: 'Aegislash', type: ['Steel', 'Ghost'] },
  { code: '682', name: 'Spritzee', type: ['Fairy'] },
  { code: '683', name: 'Aromatisse', type: ['Fairy'] },
  { code: '684', name: 'Swirlix', type: ['Fairy'] },
  { code: '685', name: 'Slurpuff', type: ['Fairy'] },
  { code: '686', name: 'Inkay', type: ['Dark', 'Psychic'] },
  { code: '687', name: 'Malamar', type: ['Dark', 'Psychic'] },
  { code: '688', name: 'Binacle', type: ['Rock', 'Water'] },
  { code: '689', name: 'Barbaracle', type: ['Rock', 'Water'] },
  { code: '690', name: 'Skrelp', type: ['Poison', 'Water'] },
  { code: '691', name: 'Dragalge', type: ['Poison', 'Dragon'] },
  { code: '692', name: 'Clauncher', type: ['Water'] },
  { code: '693', name: 'Clawitzer', type: ['Water'] },
  { code: '694', name: 'Helioptile', type: ['Electric', 'Normal'] },
  { code: '695', name: 'Heliolisk', type: ['Electric', 'Normal'] },
  { code: '696', name: 'Tyrunt', type: ['Rock', 'Dragon'] },
  { code: '697', name: 'Tyrantrum', type: ['Rock', 'Dragon'] },
  { code: '698', name: 'Amaura', type: ['Rock', 'Ice'] },
  { code: '699', name: 'Aurorus', type: ['Rock', 'Ice'] },
  { code: '700', name: 'Sylveon', type: ['Fairy'] },
  { code: '701', name: 'Hawlucha', type: ['Fighting', 'Flying'] },
  { code: '702', name: 'Dedenne', type: ['Electric', 'Fairy'] },
  { code: '703', name: 'Carbink', type: ['Rock', 'Fairy'] },
  { code: '704', name: 'Goomy', type: ['Dragon'] },
  { code: '705', name: 'Sliggoo', type: ['Dragon'] },
  { code: '706', name: 'Goodra', type: ['Dragon'] },
  { code: '707', name: 'Klefki', type: ['Steel', 'Fairy'] },
  { code: '708', name: 'Phantump', type: ['Ghost', 'Grass'] },
  { code: '709', name: 'Trevenant', type: ['Ghost', 'Grass'] },
  { code: '710', name: 'Pumpkaboo', type: ['Ghost', 'Grass'] },
  { code: '711', name: 'Gourgeist', type: ['Ghost', 'Grass'] },
  { code: '712', name: 'Bergmite', type: ['Ice'] },
  { code: '713', name: 'Avalugg', type: ['Ice'] },
  { code: '714', name: 'Noibat', type: ['Flying', 'Dragon'] },
  { code: '715', name: 'Noivern', type: ['Flying', 'Dragon'] },
  { code: '716', name: 'Xerneas', type: ['Fairy'] },
  { code: '717', name: 'Yveltal', type: ['Dark', 'Flying'] },
  { code: '718', name: 'Zygarde', type: ['Dragon', 'Ground'] },
  { code: '719', name: 'Diancie', type: ['Rock', 'Fairy'] },
  { code: '720', name: 'Hoopa', type: ['Psychic', 'Ghost'] },
  { code: '721', name: 'Volcanion', type: ['Fire', 'Water'] },
  { code: '722', name: 'Rowlet', type: ['Grass', 'Flying'] },
  { code: '723', name: 'Dartrix', type: ['Grass', 'Flying'] },
  { code: '724', name: 'Decidueye', type: ['Grass', 'Ghost'] },
  { code: '725', name: 'Litten', type: ['Fire'] },
  { code: '726', name: 'Torracat', type: ['Fire'] },
  { code: '727', name: 'Incineroar', type: ['Fire', 'Dark'] },
  { code: '728', name: 'Popplio', type: ['Water'] },
  { code: '729', name: 'Brionne', type: ['Water'] },
  { code: '730', name: 'Primarina', type: ['Water', 'Fairy'] },
  { code: '731', name: 'Pikipek', type: ['Normal', 'Flying'] },
  { code: '732', name: 'Trumbeak', type: ['Normal', 'Flying'] },
  { code: '733', name: 'Toucannon', type: ['Normal', 'Flying'] },
  { code: '734', name: 'Yungoos', type: ['Normal'] },
  { code: '735', name: 'Gumshoos', type: ['Normal'] },
  { code: '736', name: 'Grubbin', type: ['Bug'] },
  { code: '737', name: 'Charjabug', type: ['Bug', 'Electric'] },
  { code: '738', name: 'Vikavolt', type: ['Bug', 'Electric'] },
  { code: '739', name: 'Crabrawler', type: ['Fighting'] },
  { code: '740', name: 'Crabominable', type: ['Fighting', 'Ice'] },
  { code: '741', name: 'Oricorio', type: ['Fire', 'Flying'] },
  { code: '742', name: 'Cutiefly', type: ['Bug', 'Fairy'] },
  { code: '743', name: 'Ribombee', type: ['Bug', 'Fairy'] },
  { code: '744', name: 'Rockruff', type: ['Rock'] },
  { code: '745', name: 'Lycanroc', type: ['Rock'] },
  { code: '746', name: 'Wishiwashi', type: ['Water'] },
  { code: '747', name: 'Mareanie', type: ['Poison', 'Water'] },
  { code: '748', name: 'Toxapex', type: ['Poison', 'Water'] },
  { code: '749', name: 'Mudbray', type: ['Ground'] },
  { code: '750', name: 'Mudsdale', type: ['Ground'] },
  { code: '751', name: 'Dewpider', type: ['Water', 'Bug'] },
  { code: '752', name: 'Araquanid', type: ['Water', 'Bug'] },
  { code: '753', name: 'Fomantis', type: ['Grass'] },
  { code: '754', name: 'Lurantis', type: ['Grass'] },
  { code: '755', name: 'Morelull', type: ['Grass', 'Fairy'] },
  { code: '756', name: 'Shiinotic', type: ['Grass', 'Fairy'] },
  { code: '757', name: 'Salandit', type: ['Poison', 'Fire'] },
  { code: '758', name: 'Salazzle', type: ['Poison', 'Fire'] },
  { code: '759', name: 'Stufful', type: ['Normal', 'Fighting'] },
  { code: '760', name: 'Bewear', type: ['Normal', 'Fighting'] },
  { code: '761', name: 'Bounsweet', type: ['Grass'] },
  { code: '762', name: 'Steenee', type: ['Grass'] },
  { code: '763', name: 'Tsareena', type: ['Grass'] },
  { code: '764', name: 'Comfey', type: ['Fairy'] },
  { code: '765', name: 'Oranguru', type: ['Normal', 'Psychic'] },
  { code: '766', name: 'Passimian', type: ['Fighting'] },
  { code: '767', name: 'Wimpod', type: ['Bug', 'Water'] },
  { code: '768', name: 'Golisopod', type: ['Bug', 'Water'] },
  { code: '769', name: 'Sandygast', type: ['Ghost', 'Ground'] },
  { code: '770', name: 'Palossand', type: ['Ghost', 'Ground'] },
  { code: '771', name: 'Pyukumuku', type: ['Water'] },
  { code: '772', name: 'Type: Null', type: ['Normal'] },
  { code: '773', name: 'Silvally', type: ['Normal'] },
  { code: '774', name: 'Minior', type: ['Rock', 'Flying'] },
  { code: '775', name: 'Komala', type: ['Normal'] },
  { code: '776', name: 'Turtonator', type: ['Fire', 'Dragon'] },
  { code: '777', name: 'Togedemaru', type: ['Electric', 'Steel'] },
  { code: '778', name: 'Mimikyu', type: ['Ghost', 'Fairy'] },
  { code: '779', name: 'Bruxish', type: ['Water', 'Psychic'] },
  { code: '780', name: 'Drampa', type: ['Normal', 'Dragon'] },
  { code: '781', name: 'Dhelmise', type: ['Ghost', 'Grass'] },
  { code: '782', name: 'Jangmo-o', type: ['Dragon'] },
  { code: '783', name: 'Hakamo-o', type: ['Dragon', 'Fighting'] },
  { code: '784', name: 'Kommo-o', type: ['Dragon', 'Fighting'] },
  { code: '785', name: 'Tapu Koko', type: ['Electric', 'Fairy'] },
  { code: '786', name: 'Tapu Lele', type: ['Psychic', 'Fairy'] },
  { code: '787', name: 'Tapu Bulu', type: ['Grass', 'Fairy'] },
  { code: '788', name: 'Tapu Fini', type: ['Water', 'Fairy'] },
  { code: '789', name: 'Cosmog', type: ['Psychic'] },
  { code: '790', name: 'Cosmoem', type: ['Psychic'] },
  { code: '791', name: 'Solgaleo', type: ['Psychic', 'Steel'] },
  { code: '792', name: 'Lunala', type: ['Psychic', 'Ghost'] },
  { code: '793', name: 'Nihilego', type: ['Rock', 'Poison'] },
  { code: '794', name: 'Buzzwole', type: ['Bug', 'Fighting'] },
  { code: '795', name: 'Pheromosa', type: ['Bug', 'Fighting'] },
  { code: '796', name: 'Xurkitree', type: ['Electric'] },
  { code: '797', name: 'Celesteela', type: ['Steel', 'Flying'] },
  { code: '798', name: 'Kartana', type: ['Grass', 'Steel'] },
  { code: '799', name: 'Guzzlord', type: ['Dark', 'Dragon'] },
  { code: '800', name: 'Necrozma', type: ['Psychic'] },
  { code: '801', name: 'Magearna', type: ['Steel', 'Fairy'] },
  { code: '802', name: 'Marshadow', type: ['Fighting', 'Ghost'] },
  { code: '803', name: 'Poipole', type: ['Poison'] },
  { code: '804', name: 'Naganadel', type: ['Poison', 'Dragon'] },
  { code: '805', name: 'Stakataka', type: ['Rock', 'Steel'] },
  { code: '806', name: 'Blacephalon', type: ['Fire', 'Ghost'] },
  { code: '807', name: 'Zeraora', type: ['Electric'] },
  { code: '808', name: 'Meltan', type: ['Steel'] },
  { code: '809', name: 'Melmetal', type: ['Steel'] },
  { code: '810', name: 'Grookey', type: ['Grass'] },
  { code: '811', name: 'Thwackey', type: ['Grass'] },
  { code: '812', name: 'Rillaboom', type: ['Grass'] },
  { code: '813', name: 'Scorbunny', type: ['Fire'] },
  { code: '814', name: 'Raboot', type: ['Fire'] },
  { code: '815', name: 'Cinderace', type: ['Fire'] },
  { code: '816', name: 'Sobble', type: ['Water'] },
  { code: '817', name: 'Drizzile', type: ['Water'] },
  { code: '818', name: 'Inteleon', type: ['Water'] },
  { code: '819', name: 'Skwovet', type: ['Normal'] },
  { code: '820', name: 'Greedent', type: ['Normal'] },
  { code: '821', name: 'Rookidee', type: ['Flying'] },
  { code: '822', name: 'Corvisquire', type: ['Flying'] },
  { code: '823', name: 'Corviknight', type: ['Flying', 'Steel'] },
  { code: '824', name: 'Blipbug', type: ['Bug'] },
  { code: '825', name: 'Dottler', type: ['Bug', 'Psychic'] },
  { code: '826', name: 'Orbeetle', type: ['Bug', 'Psychic'] },
  { code: '827', name: 'Nickit', type: ['Dark'] },
  { code: '828', name: 'Thievul', type: ['Dark'] },
  { code: '829', name: 'Gossifleur', type: ['Grass'] },
  { code: '830', name: 'Eldegoss', type: ['Grass'] },
  { code: '831', name: 'Wooloo', type: ['Normal'] },
  { code: '832', name: 'Dubwool', type: ['Normal'] },
  { code: '833', name: 'Chewtle', type: ['Water'] },
  { code: '834', name: 'Drednaw', type: ['Water', 'Rock'] },
  { code: '835', name: 'Yamper', type: ['Electric'] },
  { code: '836', name: 'Boltund', type: ['Electric'] },
  { code: '837', name: 'Rolycoly', type: ['Rock'] },
  { code: '838', name: 'Carkol', type: ['Rock', 'Fire'] },
  { code: '839', name: 'Coalossal', type: ['Rock', 'Fire'] },
  { code: '840', name: 'Applin', type: ['Grass', 'Dragon'] },
  { code: '841', name: 'Flapple', type: ['Grass', 'Dragon'] },
  { code: '842', name: 'Appletun', type: ['Grass', 'Dragon'] },
  { code: '843', name: 'Silicobra', type: ['Ground'] },
  { code: '844', name: 'Sandaconda', type: ['Ground'] },
  { code: '845', name: 'Cramorant', type: ['Flying', 'Water'] },
  { code: '846', name: 'Arrokuda', type: ['Water'] },
  { code: '847', name: 'Barraskewda', type: ['Water'] },
  { code: '848', name: 'Toxel', type: ['Electric', 'Poison'] },
  { code: '849', name: 'Toxtricity', type: ['Electric', 'Poison'] },
  { code: '850', name: 'Sizzlipede', type: ['Fire', 'Bug'] },
  { code: '851', name: 'Centiskorch', type: ['Fire', 'Bug'] },
  { code: '852', name: 'Clobbopus', type: ['Fighting'] },
  { code: '853', name: 'Grapploct', type: ['Fighting'] },
  { code: '854', name: 'Sinistea', type: ['Ghost'] },
  { code: '855', name: 'Polteageist', type: ['Ghost'] },
  { code: '856', name: 'Hatenna', type: ['Psychic'] },
  { code: '857', name: 'Hattrem', type: ['Psychic'] },
  { code: '858', name: 'Hatterene', type: ['Psychic', 'Fairy'] },
  { code: '859', name: 'Impidimp', type: ['Dark', 'Fairy'] },
  { code: '860', name: 'Morgrem', type: ['Dark', 'Fairy'] },
  { code: '861', name: 'Grimmsnarl', type: ['Dark', 'Fairy'] },
  { code: '862', name: 'Obstagoon', type: ['Dark', 'Normal'] },
  { code: '863', name: 'Perrserker', type: ['Steel'] },
  { code: '864', name: 'Cursola', type: ['Ghost'] },
  { code: '865', name: 'Sirfetch’d', type: ['Fighting'] },
  { code: '866', name: 'Mr. Rime', type: ['Ice', 'Psychic'] },
  { code: '867', name: 'Runerigus', type: ['Ground', 'Ghost'] },
  { code: '868', name: 'Milcery', type: ['Fairy'] },
  { code: '869', name: 'Alcremie', type: ['Fairy'] },
  { code: '870', name: 'Falinks', type: ['Fighting'] },
  { code: '871', name: 'Pincurchin', type: ['Electric'] },
  { code: '872', name: 'Snom', type: ['Ice', 'Bug'] },
  { code: '873', name: 'Frosmoth', type: ['Ice', 'Bug'] },
  { code: '874', name: 'Stonjourner', type: ['Rock'] },
  { code: '875', name: 'Eiscue', type: ['Ice'] },
  { code: '876', name: 'Indeedee', type: ['Psychic', 'Normal'] },
  { code: '877', name: 'Morpeko', type: ['Electric', 'Dark'] },
  { code: '878', name: 'Cufant', type: ['Steel'] },
  { code: '879', name: 'Copperajah', type: ['Steel'] },
  { code: '880', name: 'Dracozolt', type: ['Electric', 'Dragon'] },
  { code: '881', name: 'Arctozolt', type: ['Electric', 'Ice'] },
  { code: '882', name: 'Dracovish', type: ['Water', 'Dragon'] },
  { code: '883', name: 'Arctovish', type: ['Water', 'Ice'] },
  { code: '884', name: 'Duraludon', type: ['Steel', 'Dragon'] },
  { code: '885', name: 'Dreepy', type: ['Dragon', 'Ghost'] },
  { code: '886', name: 'Drakloak', type: ['Dragon', 'Ghost'] },
  { code: '887', name: 'Dragapult', type: ['Dragon', 'Ghost'] },
  { code: '888', name: 'Zacian', type: ['Fairy'] },
  { code: '889', name: 'Zamazenta', type: ['Fighting'] },
  { code: '890', name: 'Eternatus', type: ['Poison', 'Dragon'] },
  { code: '891', name: 'Kubfu', type: ['Fighting'] },
  { code: '892', name: 'Urshifu', type: ['Fighting', 'Dark'] },
  { code: '893', name: 'Zarude', type: ['Dark', 'Grass'] },
  { code: '894', name: 'Regieleki', type: ['Electric'] },
  { code: '895', name: 'Regidrago', type: ['Dragon'] },
  { code: '896', name: 'Glastrier', type: ['Ice'] },
  { code: '897', name: 'Spectrier', type: ['Ghost'] },
  { code: '898', name: 'Calyrex', type: ['Psychic', 'Grass'] },
  { code: '899', name: 'Wyrdeer', type: ['Normal', 'Psychic'] },
  { code: '900', name: 'Kleavor', type: ['Bug', 'Rock'] },
  { code: '901', name: 'Snom', type: ['Ice', 'Bug'] },
  { code: '902', name: 'Frosmoth', type: ['Ice', 'Bug'] },
  { code: '903', name: 'Stonjourner', type: ['Rock'] },
  { code: '904', name: 'Eiscue', type: ['Ice'] },
  { code: '905', name: 'Indeedee', type: ['Psychic', 'Normal'] },
  { code: '906', name: 'Morpeko', type: ['Electric', 'Dark'] },
  { code: '907', name: 'Cufant', type: ['Steel'] },
  { code: '908', name: 'Copperajah', type: ['Steel'] },
  { code: '909', name: 'Dracozolt', type: ['Electric', 'Dragon'] },
  { code: '910', name: 'Arctozolt', type: ['Electric', 'Ice'] },
  { code: '911', name: 'Duraludon', type: ['Steel', 'Dragon'] },
  { code: '912', name: 'Dreepy', type: ['Dragon', 'Ghost'] },
  { code: '913', name: 'Drakloak', type: ['Dragon', 'Ghost'] },
  { code: '914', name: 'Dragapult', type: ['Dragon', 'Ghost'] },
  { code: '915', name: 'Zacian', type: ['Fairy'] },
  { code: '916', name: 'Zamazenta', type: ['Fighting'] },
  { code: '917', name: 'Eternatus', type: ['Poison', 'Dragon'] },
  { code: '918', name: 'Kubfu', type: ['Fighting'] },
  { code: '919', name: 'Urshifu', type: ['Fighting', 'Dark'] },
  { code: '920', name: 'Zarude', type: ['Dark', 'Grass'] },
  { code: '921', name: 'Regieleki', type: ['Electric'] },
  { code: '922', name: 'Regidrago', type: ['Dragon'] },
  { code: '923', name: 'Glastrier', type: ['Ice'] },
  { code: '924', name: 'Spectrier', type: ['Ghost'] },
  { code: '925', name: 'Calyrex', type: ['Psychic', 'Grass'] },
  { code: '926', name: 'Shielddon', type: ['Steel', 'Dragon'] },
  { code: '927', name: 'Phalanx', type: ['Fighting'] },
  { code: '928', name: 'Zamazenta', type: ['Fighting', 'Steel'] },
  { code: '929', name: 'Eternatus', type: ['Poison', 'Dragon'] },
  { code: '930', name: 'Kubfu', type: ['Fighting'] },
  { code: '931', name: 'Urshifu', type: ['Fighting', 'Dark'] },
  { code: '932', name: 'Zarude', type: ['Dark', 'Grass'] },
  { code: '933', name: 'Regieleki', type: ['Electric'] },
  { code: '934', name: 'Regidrago', type: ['Dragon'] },
  { code: '935', name: 'Glastrier', type: ['Ice'] },
  { code: '936', name: 'Spectrier', type: ['Ghost'] },
  { code: '937', name: 'Calyrex', type: ['Psychic', 'Grass'] },
  { code: '938', name: 'Shielddon', type: ['Steel', 'Dragon'] },
  { code: '939', name: 'Phalanx', type: ['Fighting'] },
  { code: '940', name: 'Zamazenta', type: ['Fighting', 'Steel'] },
  { code: '941', name: 'Eternatus', type: ['Poison', 'Dragon'] },
  { code: '942', name: 'Kubfu', type: ['Fighting'] },
  { code: '943', name: 'Urshifu', type: ['Fighting', 'Dark'] },
  { code: '944', name: 'Zarude', type: ['Dark', 'Grass'] },
  { code: '945', name: 'Regieleki', type: ['Electric'] },
  { code: '946', name: 'Regidrago', type: ['Dragon'] },
  { code: '947', name: 'Glastrier', type: ['Ice'] },
  { code: '948', name: 'Spectrier', type: ['Ghost'] },
  { code: '949', name: 'Calyrex', type: ['Psychic', 'Grass'] },
  { code: '950', name: 'Shielddon', type: ['Steel', 'Dragon'] },
  { code: '951', name: 'Phalanx', type: ['Fighting'] },
  { code: '952', name: 'Zamazenta', type: ['Fighting', 'Steel'] },
  { code: '953', name: 'Eternatus', type: ['Poison', 'Dragon'] },
  { code: '954', name: 'Kubfu', type: ['Fighting'] },
  { code: '955', name: 'Urshifu', type: ['Fighting', 'Dark'] },
  { code: '956', name: 'Zarude', type: ['Dark', 'Grass'] },
  { code: '957', name: 'Regieleki', type: ['Electric'] },
  { code: '958', name: 'Regidrago', type: ['Dragon'] },
  { code: '959', name: 'Glastrier', type: ['Ice'] },
  { code: '960', name: 'Spectrier', type: ['Ghost'] },
  { code: '961', name: 'Calyrex', type: ['Psychic', 'Grass'] },
  { code: '962', name: 'Shielddon', type: ['Steel', 'Dragon'] },
  { code: '963', name: 'Phalanx', type: ['Fighting'] },
  { code: '964', name: 'Zamazenta', type: ['Fighting', 'Steel'] },
  { code: '965', name: 'Eternatus', type: ['Poison', 'Dragon'] },
  { code: '966', name: 'Kubfu', type: ['Fighting'] },
  { code: '967', name: 'Urshifu', type: ['Fighting', 'Dark'] },
  { code: '968', name: 'Zarude', type: ['Dark', 'Grass'] },
  { code: '969', name: 'Regieleki', type: ['Electric'] },
  { code: '970', name: 'Regidrago', type: ['Dragon'] },
  { code: '971', name: 'Glastrier', type: ['Ice'] },
  { code: '972', name: 'Spectrier', type: ['Ghost'] },
  { code: '973', name: 'Calyrex', type: ['Psychic', 'Grass'] },
  { code: '974', name: 'Shielddon', type: ['Steel', 'Dragon'] },
  { code: '975', name: 'Phalanx', type: ['Fighting'] },
  { code: '976', name: 'Zamazenta', type: ['Fighting', 'Steel'] },
  { code: '977', name: 'Eternatus', type: ['Poison', 'Dragon'] },
  { code: '978', name: 'Kubfu', type: ['Fighting'] },
  { code: '979', name: 'Urshifu', type: ['Fighting', 'Dark'] },
  { code: '980', name: 'Zarude', type: ['Dark', 'Grass'] },
  { code: '981', name: 'Regieleki', type: ['Electric'] },
  { code: '982', name: 'Regidrago', type: ['Dragon'] },
  { code: '983', name: 'Glastrier', type: ['Ice'] },
  { code: '984', name: 'Spectrier', type: ['Ghost'] },
  { code: '985', name: 'Calyrex', type: ['Psychic', 'Grass'] },
  { code: '986', name: 'Shielddon', type: ['Steel', 'Dragon'] },
  { code: '987', name: 'Phalanx', type: ['Fighting'] },
  { code: '988', name: 'Zamazenta', type: ['Fighting', 'Steel'] },
  { code: '989', name: 'Eternatus', type: ['Poison', 'Dragon'] },
  { code: '990', name: 'Kubfu', type: ['Fighting'] },
  { code: '991', name: 'Urshifu', type: ['Fighting', 'Dark'] },
  { code: '992', name: 'Zarude', type: ['Dark', 'Grass'] },
  { code: '993', name: 'Regieleki', type: ['Electric'] },
  { code: '994', name: 'Regidrago', type: ['Dragon'] },
  { code: '995', name: 'Glastrier', type: ['Ice'] },
  { code: '996', name: 'Spectrier', type: ['Ghost'] },
  { code: '997', name: 'Calyrex', type: ['Psychic', 'Grass'] },
  { code: '998', name: 'Shielddon', type: ['Steel', 'Dragon'] },
  { code: '999', name: 'Phalanx', type: ['Fighting'] },
  { code: '1000', name: 'Zamazenta', type: ['Fighting', 'Steel'] },
  { code: '1001', name: 'Eternamax Eternatus', type: ['Poison', 'Dragon'] },
  { code: '1002', name: 'Kubfu', type: ['Fighting'] },
  { code: '1003', name: 'Urshifu', type: ['Fighting', 'Dark'] },
  { code: '1004', name: 'Urshifu', type: ['Fighting', 'Water'] },
  { code: '1005', name: 'Zarude', type: ['Dark', 'Grass'] },
  { code: '1006', name: 'Regieleki', type: ['Electric'] },
  { code: '1007', name: 'Regidrago', type: ['Dragon'] },
  { code: '1008', name: 'Glastrier', type: ['Ice'] },
  { code: '1009', name: 'Spectrier', type: ['Ghost'] },
  { code: '1010', name: 'Calyrex', type: ['Psychic', 'Grass'] },
  ];
  export { pokemons };